version: '3.1'
services:

  app:
    container_name: springboot-courseword
    image: springboot-postgresql
    build: ./
    ports:
      - "7777:8080"
    environment:
      - UPLOAD_PATH=.
      - UPLOAD_PATH_WITHOUT_IMAGES=.
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis
#    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.11
    ports:
      - "8080:80"
    volumes:
      - ./src/main/resources/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/main/resources/templates/main.html:/data/static/main.html

