version: '3.1'
services:

  app:
    container_name: springboot-courseword
    image: springboot-postgresql
    build: ./
    ports:
      - "7777:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - SPRING_REDIS_ADDRESS=redis
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

#  nginx:
#    image: nginx:1.11
#    ports:
#      - "8080:80"
#    volumes:
#      - ./src/main/resources/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./src/main/resources/templates/main.html:/data/static/main.html

